apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: fluxcdtutorial
spec:
  encryptedData:
    token: AgCBrCE9tSAtaOwZKlSCMUGcTvsjc0eYy1jhpcEUM9T2gMb5eBdrQy+WAvbZefylI28Dj2mFPCqGEA5660Sc/i7PhcwR2mK4iGzZqTdbJFaw2fvZq9Xd/LEaoxhugnqiSOJ6XWhNDWLPAqLM6YrVz7Lpn6/AP5lOkKOsrXeVnpqBpF+nsnMxShLrUUCCCjymaYE3/OnSg5ymUZsOM+6P9iViAmWepuw6IqKVmqmPwBp5saVScMT9ifIvzluAWmNqKvge0BLhDwpZLn4HnwvP/aDjM9wtrr8hjOkBtcfrYVr0Lo7PxXvHjBDxvntPKx4DZgrWhlqZKyDq4RLlD2meZ8CrB8NGm1viM3CKjYPKA1iSgQG7wuwEQWJyB4/FCffzU95dCpktcrbuGSWFIXKpITRwHcP7g5XHGOz4nbS18mLpO3OFz/2jzZEml4ucoQNDzECAzY/EgtIz5lu7shPMcQeaJdAfZsPTRkhZDkFO7vC3r56Ko71MkaFFR7VDSmPOeq56MXQSAz43LDT/ZmO58Troec0bg1QxUWGSO+MPJ3Ih4pl9yAee1ppUevkZdAK2EYk0Livhdb/LWRy4bba9UJcZagFaYT4jU1way1siqVbXjSw6cu54XFhoIAJPnTrZ1j5itUwC6UIsA2S7xT1Kpg19j5libsMZGmD4DhT4Ns8zxIW+LCx1bt4sxVGgaM8c18vm4M7vQUaHWaLDUv5Rzl0sZbwl5SYGcNqri/XwW/LsP3Qm4xXeqs+q
  template:
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: fluxcdtutorial

