apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: fluxcdtutorial
spec:
  encryptedData:
    password: AgBPW67DWi9TUW+Uh9BSZDe05dbs8JivlxgCnaGsgD8ap8jhazrUbia+AYP1li+6gfwZe/h2cy24oMrEgJ1ERDWC2lP0RCoi+ncC+iuMyIoCwwBVHjNx7E5iQdyyEru0aFMTQNgpB1/iTLdi3EJoCn5Z6CE6YFEo19LIiVzzo6Te1diotVw3MgsJJFWS6F8l9wROz8IxVsr8CY0oj37WHxM6lEyAkBsZ+qOR0E+ju7jXhc1uCegMfVxh+ShUARpgbvKcUVmI3Pkj0PxlC1uhNlsmpDirTBaeLE3xuHYu99/ZEluH3vg5sHOVLF67v41VbZSgmpcxqI1LCQDBZocdKTOjJcpU38WslLQ8wTxevUTtgSVXU/q9PJvGK5rbtXs6YR6SJwJ4UTHJMZF/dBfs7qF5VYNBz7DqTTIxtrnzST5u0hrNMWW+TA4D03Ra83TNnkfwBSbf8gUoWlUit/KvaYYGNs4WXhWQAhVLLRhN0jJc6Lng+Xg9eOpIcZD6aemhWgrCvyf1vne/4bxQQsf6cNmGFT+TVaySJ61fGZXDH1VnMsBlJIZRPQCER57gjO8Y7J9GM7iOpBwJQFmmaGOKGuPykVElIIk+CbTX4CXxCNu5LgNSV1iD6HsV8BTGcG30y403pxdLlypAyHqCiInpLt7bhvhCg2koCxEdcgstDr3BoYsyh3gFbcqao3F/dEx1/Iyf5IhinFkBFw2y26Yk+h7ZcBTHGXu4hNkkgDGZ3/DLaQAySCD//c/V
    username: AgB0hCaAfk9n4dobzVEwT9qYG7IZVFefkeOF5+OuImdQKGBL4O0KGecEf1NYA0bFB3e8TzO6MxcvLCx8KmXb0mZLFCiMSQGh0bsfxEOfRtnqluB+QGmVOowFz6AC8B9+vCGLfITsjfYTlYQjIHwsJiNcFOLLQ034X6AZ5xdzH93+orRGocuX6em1yfqmPpXaZc0b0fHIzEq0GgNXfA07Zrx/uAIcflAdpttqGAg9DVs4ReRRblKOThVbbL9Bub0vjwbzNZHkmrB9llPn3Vrxe1MiFpogjIUqxBUFvB8uwBFDx3i/skcFflxtoqjmAd5gqfB0O9dXsENCi2VJVHRWaydPFx6f6+n78AMhug9ZM27mP3ArhJqfF2c4nJhkk3Q97uHICWyPkK8Lwft7av714qbXWBYjrUtLpG2s+akzQODPfgu4DViFCYRGsUYZODhSUwnt8Hg6jb3o8aLEVcS7m7q4kprcicIYPeA+dZHA3z3uOy7CcFi4dH8QGbKDUz/rhxlfrWmGws+rDs4EGqURJG8R19m6CSyJtYRiySrrv7b5Yd/RnOXVFjkbGx89PNnIwtCnXtnBo+WnhtpQfvN8g3eBxqMx44DiKXsAvnZMAecDrsEF/3gCW+4jUYrVp/gT9Ru+X09xGRb9dH+vGQY6KZSHG2q5pilwfjgoIPOQySFkv5I6GHli0uppoQwcM+H35JVlPkWzY7GWzuw=
  template:
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: fluxcdtutorial

